credentials:
  usernames:
    angelo_david:
      email: angelocalderon.davila@gmail.com
      name: Angelo Calderon
      password: 61b7bd0b5bfb565c729870992ed83b3555c34e4b
    sebomaro2103:
      email: sebastianmontenegrorangel@gmail.com
      name: Sebastián Montenegro
      password: $2b$12$wWBu2.mFAJGDfBNHrAmxq.g7aEY6CZRgUNDAXYrWH9QWBs.O9F6mK # Password hasheada de "sebomaro2103"
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  - sebastianmontenegrorangel@gmail.com
  - angelocalderon.davila@gmail.com
