credentials:
  usernames:
    sebomaro2103:
      email: sebastianmontenegrorangel@gmail.com
      name: Sebastián Montenegro
      password: $2b$12$wWBu2.mFAJGDfBNHrAmxq.g7aEY6CZRgUNDAXYrWH9QWBs.O9F6mK # Password hasheada de "sebomaro2103"
    adminangelo:
      email: angelocalderon.davila@gmail.com
      name: Angelo Calderon
      password: $2b$12$YmCOR/B5VHAQ.z4R84YHw.yhqA5ZNOaIvGLDyHgxnPNGVxFQVY2aO # contraseña: AdminAngelo2024
    marianmontenegrorangel:
      email: marianmontenegrorangel@gmail.com
      name: Marian Montnegro
      password: $2b$12$mNpBjXFxjcYMpgO7Ou9tBeFgCCEaKtw0ZFE7gRbRKVG/ZNKLcUY6q
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  - sebastianmontenegrorangel@gmail.com
  - angelocalderon.davila@gmail.com
  - marianmontenegrorangel@gmail.com
