credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$abcdefghijklmnopqrstuvwxyz12345678901234567890 # Esta es una contraseña hasheada
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  - melsby@gmail.com